import { type NextPage } from "next";
import Head from "next/head";
import { useState, useEffect, useMemo } from "react";

//import Link from "next/link";

import { api } from "~/utils/api";
import { getOptionsForVote } from "~/utils/getRandomCuisine";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "123" });
  // const num  = api.num.calc.useQuery({id: 10});
  const btn =
  "inline-flex items-center px-3 py-1.5 border border-gray-300 shadow-sm font-medium rounded-full text-gray-700 bg-white hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500";
  
  const [first, setFirst] = useState<number>(0);
  const [second, setSecond] = useState<number>(0);
  const fetchData = () => {
    const optionsResponse = getOptionsForVote() as [number, number];

    setFirst(optionsResponse[0]);
    setSecond(optionsResponse[1]);
  };

  useEffect(() => { 
    fetchData();
  }, []);


  // const [ids, setIds] = useState(() => getOptionsForVote());

  // const [first,second] = ids;

  const voteForTastiest = (selected: number) => {

    fetchData();
  }


  return (
    <>
      <Head>
        <title>Tastiest Cuisine</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen flex flex-col justify-center items-center">

        <div className="text-2xl text-center">Which Cuisine is Tastier?</div>
        <div className="p-2"/>
        <div className="border rounded p-8 flex justify-between items-center max-w-2xl">
          <div className="w-64 h-64  flex flex-col items-center justify-center">
            <div>
              {first}
            </div>
            <button className={btn} onClick={() => voteForTastiest(first)}>
              Tastier
            </button>
          </div>
          <div className="p-8">Vs</div>
          <div className="w-64 h-64  flex flex-col items-center justify-center">
            <div>
              {second}
            </div>
            <button className={btn} onClick={() => voteForTastiest(second)}>
              Tastier
            </button>
          </div>

        </div>
        

        {/* <p className="text-2xl text-white">
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          {num.data ? num.data.greeting : "Loading tRPC query..."}
          
        </p> */}
      </main>
    </>
  );
};

export default Home;
